- name: web for nginx deploy on ubuntu
  hosts: localhost
  become: yes
  vars:
    domain: jenkins.trycloud.co.in
    ansible_user: root  
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600
     
  - name: Allow all access to tcp port 80
    ufw:
      rule: allow
      port: '80'
      proto: tcp    
    
  - name: "install nginx"
    apt:
      name: ['nginx']
      state: latest

  - name: "create www directory"
    file:
      path: /var/www/{{ domain }}/html
      state: directory
      mode: '0775'
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: delete default nginx site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: copy nginx site.conf
    template:
      src: site.conf.j2
      dest: /etc/nginx/sites-enabled/{{ domain }}
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx
    
  
  - name: "sync website"
    synchronize:
      src: site/
      dest: /var/www/{{ domain }}/html
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
    become: no    

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
